FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Rovio.Matchmaking.slnx ./
COPY src/ ./src/
RUN dotnet restore src/Rovio.Matchmaking.Worker/Rovio.Matchmaking.Worker.csproj
RUN dotnet publish src/Rovio.Matchmaking.Worker/Rovio.Matchmaking.Worker.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Rovio.Matchmaking.Worker.dll"]
