// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rovio.Matchmaking.Infrastructure.Persistence;

#nullable disable

namespace Rovio.Matchmaking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MatchmakingDbContext))]
    partial class MatchmakingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rovio.Matchmaking.Infrastructure.Persistence.GameMatchConfigEntity", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("game_id");

                    b.Property<bool>("AllowLateJoin")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_late_join");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("LatencyPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("latency_policy_json");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int?>("MaxQueueDepth")
                        .HasColumnType("integer")
                        .HasColumnName("max_queue_depth");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("min_players");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GameId");

                    b.ToTable("game_match_configs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
